name: Fix styling

on:
  pull_request:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - uses: ./.github/actions/composer-install

      - name: Execute php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          PHP_CS_FIXER_IGNORE_ENV: true
        with:
          commit_message: Fix styling
